site_name: Feature Engineering Portfolio
site_description: Practical Feature Engineering for Machine Learning
site_author: Josue

theme:
  name: material

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - search.highlight

nav:

  - Home: index.md

  - Machine Learning Foundations:

      - What is Feature Engineering:
          foundations/what_is_feature_engineering.md

      - Feature Target Relationship:
          foundations/feature_target_relationship.md

      - Baseline Model:
          foundations/baseline_model.md

  - Feature Engineering:

      - Feature Discovery:
          feature_engineering/feature_discovery.md

  - Practical Case Study:

      - House Prices:
          practical_cases/house_prices.md

      - Results:
          practical_cases/results.md
          
  - Practical Case Study:
      - House Prices Notebook: practical_cases/house_prices.ipynb

plugins:
  - search
  - mkdocs-jupyter